### ISSUE TITLE
long double 

### ISSUE THREAD

**Issue by infoshoc** [IlyaCk/CkOlympInformTutorial#2]
Я, чесно кажучи, не дуже впевнений у тому, що long double завжди працює швидко. 
Бо були у мене якісь коди, що TL-ли, а коли я міняв long double на double, починали укладатися. Правда, я не дуже глибоко досліджував це питання, можливо там були ще якісь підводні камні.
І ще я пам'ятаю, що на лекції issps про Фурьє нам рекомендували застосовувати саме double, через проблему з часом.

**Comment by IlyaCk** [comment]
Agree.

Виявляється, це я стару ситуацію з real vs extended у досить старих паскалях неправомірно узагальнив і досі не_усвідомлював цього. 
Причому, сьогодні пробував на різних комбінаціях заліза&компілятора, власне кода (чи відносно великий масив чи багато обчислень але в малій кількості змінних) -- внятної залежності не_бачу, тупо в різних обставинах по-різному, але "більшістю голосів" (по цій не_факт чи презентативній виборці) long double таки повільніший. Доходжу висновку: це такий момент, що при настільки слабкому рівні розуміння його краще просто вилучити.
